name: Generate Stats for Abdul

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # User Details
          user: AbdulRehman-18
          filename: github-metrics.svg
          
          # ðŸ“‰ SIZE FIX: "Compact" Mode
          # We only keep the header. We REMOVE 'activity', 'community', and 'repositories' text.
          base: header
          config_timezone: Asia/Kolkata
          
          # Make it wide and short (Banner style)
          config_display: large
          
          # 1. Languages (Visual Bar)
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          
          # 2. 3D Calendar (The Pyramid)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year # 6 Months is shorter/cleaner than full year
          
          # 3. Habits (Simple Graph)
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: no # Removes the text text "You code mostly in day..."
          plugin_habits_charts: yes

          # Save
          output_action: commit
          committer_branch: output
          committer_message: "Update ultra-minimal metrics"
